### PR TITLE
PROD-1286 passing through a date as the onChange value wasn't being updated.

### PR DESCRIPTION
**Pull request by reecemillsom**
#### What does this PR do? (please provide any background)

This test passes through a date to choose if we have selected one if not picks the start date.
#### What tests does this PR have?

Unit tests
#### How can this be tested?

Clone the repository
Go to my branch test-fix
Run npm start
Go to http://localhost:3000/example.html
Open console make sure get no errors while doing the following:
•Make sure when you change the start date the end date is 6 days forward.
•Click the second date field and make sure cant go before the start date.
•Make sure can still change times to what you need.

Example of the above: http://recordit.co/SQlrpioEfY
#### Screenshots / Screencast

Same as the above: http://recordit.co/SQlrpioEfY
#### What gif best describes how you feel about this work?

---
- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.
#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** *
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by DuncanFenning** [comment]
Got :eyes: on :one:

**Comment by rahulpatel** [comment]
Taking :two:

**Comment by DuncanFenning** [comment]
Tests pass and have seen functionality working on Reece's machine :+1:

**Comment by rahulpatel** [comment]
Everything seems to be in order here! :+1:

**Pull request merged**
