### PR TITLE
PROD-1247 updating react-date-time-range to react v0.14

### PR DESCRIPTION
**Pull request by reecemillsom**
#### What does this PR do? (please provide any background)

This PR updates the react-date-time-range to react v0.14+
#### What tests does this PR have?

This PR has unit tests. use npm test
#### How can this be tested?

run npm start go to the localhost link it provides and make sure that it works.
http://localhost:3000/example.html
#### Screenshots / Screencast

http://grab.by/NHfo
#### What gif best describes how you feel about this work?

---
- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.
#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** *
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by tompricetech** [comment]
Taking :one:

**Comment by tompricetech** [comment]
Looks good :+1:

**Comment by jackdclark** [comment]
Taking :two:

**Comment by jackdclark** [comment]
:+1:

**Pull request merged**
